### ISSUE TITLE
Need to use specifically formatted CifData

### ISSUE THREAD

**Issue by danieleongari** [lsmo-epfl/aiida-qeq#10]
Because of this issue of egulp (https://github.com/danieleongari/egulp/issues/6) it is mandatory to use CifData where the `_atom_site_charge` is present.

**Comment by danieleongari** [comment]
Soved on egulp

**Comment by ltalirz** [comment]
is that true?
just to be sure, what I fixed was the issue with the empty lines.
I didn't change anything related to `_atom_site_charge`
