### ISSUE TITLE
Improve the Qeq parser to recognize if the calculation failed

### ISSUE THREAD

**Issue by danieleongari** [lsmo-epfl/aiida-qeq#8]
In certain circumstances the Qeq calculation with egulp fails ant it prints `nan` for charges:
For example (`uuid: 888a424a-82c1-499b-9126-3ce75d107b00` for COF `17131N2`):
```
[...]
preparing K sum: number of K-vectors in k sum is 168
orbital corrections loop    2    2    4
iteration #50
Cycle:   50 Qdiff:          nan
SCF NOT CONVERGED
Final charges from Qeq:
   1    1         -nan
   2    1         -nan
   3    1         -nan
   4    1         -nan
   5    1         -nan
   6    1         -nan
   7    1         -nan
   8    1         -nan
   9    1         -nan
  10    1         -nan
  11    1         -nan
[...]
```

The parser should recognize that this is happening and print a warning somewhere.

**Comment by ltalirz** [comment]
Thanks, I fully agree. Can you specify an algorithm for detecting this?

E.g. is it enough to simply search for `SCF NOT CONVERGED` in the output?
Or is there a better way?

**Comment by danieleongari** [comment]
As soon as I have some time I will check what are the problems that one can have from egulp: I will inspect the 14 failure (over 2338) that I had in https://pubs.acs.org/doi/10.1021/acs.jctc.8b00669 (Table 4, egulp is Periodic-Qeq, PQeq)

**Comment by danieleongari** [comment]
I think it is fine for the moment to look for `SCF NOT CONVERGED`
It is less clear to me what is the best way to raise an exception so that the user notice it and understand that it is a problem of the algorithm and not in the aiida management. What's the best AiiDA practice for that?

**Comment by ltalirz** [comment]
fixed in https://github.com/lsmo-epfl/aiida-qeq/pull/11
